### ISSUE TITLE
Getting \b\n\r\177INCORRECT for valid Tacacs user

### ISSUE THREAD

**Issue by stevetavve** [daveolson53/pam_tacplus#2]
Using Wireshark, I see that I am getting 

Password: \b\n\r\177INCORRECT

from the Tacacs server even when I provide the correct password for the Tacacs user.

In the debug logs I see:

```
[root@localhost ~]# cat /var/log/debug.log 
Mar 30 16:39:13 localhost sshd[1199]: Invalid user tacacsAdmin from 10.254.1.180
Mar 30 16:39:13 localhost sshd[1199]: input_userauth_request: invalid user tacacsAdmin [preauth]
Mar 30 16:39:34 localhost PAM-tacplus[1199]: 1 servers defined
Mar 30 16:39:34 localhost PAM-tacplus[1199]: server[0] { addr=10.254.1.117:49, key='andy' }
Mar 30 16:39:34 localhost PAM-tacplus[1199]: tac_service=''
Mar 30 16:39:34 localhost PAM-tacplus[1199]: tac_protocol=''
Mar 30 16:39:34 localhost PAM-tacplus[1199]: tac_prompt=''
Mar 30 16:39:34 localhost PAM-tacplus[1199]: tac_login=''
Mar 30 16:39:34 localhost sshd[1199]: pam_sm_authenticate: called (pam_tacplus v1.3.8)
Mar 30 16:39:34 localhost sshd[1199]: pam_sm_authenticate: user [tacacsAdmin] obtained
Mar 30 16:39:34 localhost sshd[1199]: tacacs_get_password: called
Mar 30 16:39:34 localhost sshd[1199]: tacacs_get_password: obtained password
Mar 30 16:39:34 localhost sshd[1199]: pam_sm_authenticate: password obtained
Mar 30 16:39:34 localhost sshd[1199]: pam_sm_authenticate: tty [ssh] obtained
Mar 30 16:39:34 localhost sshd[1199]: pam_sm_authenticate: rhost [tron.tavve.com] obtained
Mar 30 16:39:34 localhost sshd[1199]: find_tac_server: trying srv 0
Mar 30 16:39:34 localhost sshd[1199]: tacacs status: TAC_PLUS_AUTHEN_STATUS_FAIL
Mar 30 16:39:34 localhost PAM-tacplus[1199]: auth failed 2
Mar 30 16:39:34 localhost sshd[1199]: find_tac_server: active srv 0
Mar 30 16:39:34 localhost sshd[1199]: pam_sm_authenticate: exit with pam status: 7
Mar 30 16:39:34 localhost sshd[1199]: pam_unix(sshd:auth): check pass; user unknown
Mar 30 16:39:34 localhost sshd[1199]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=tron.tavve.com
Mar 30 16:39:35 localhost sshd[1199]: Failed password for invalid user tacacsAdmin from 10.254.1.180 port 46888 ssh2
Mar 30 16:40:01 localhost anacron[4257]: Job `cron.weekly' started
Mar 30 16:40:01 localhost anacron[4257]: Job `cron.weekly' terminated
Mar 30 16:40:01 localhost systemd: Started Session 15 of user root.
Mar 30 16:40:01 localhost systemd: Starting Session 15 of user root.
Mar 30 16:40:01 localhost CROND[1205]: (root) CMD (/usr/lib64/sa/sa1 1 1)
Mar 30 16:40:04 localhost sshd[1199]: Connection closed by 10.254.1.180 [preauth]

```

I've created the tacacs users tacacs0..15

```
[root@localhost ~]# ll /home
total 64
drwx------ 2 tacacs0  tacacs0  4096 Mar 30 16:25 tacacs0
drwx------ 2 tacacs1  tacacs1  4096 Mar 30 16:32 tacacs1
drwx------ 2 tacacs10 tacacs10 4096 Mar 30 16:33 tacacs10
drwx------ 2 tacacs11 tacacs11 4096 Mar 30 16:33 tacacs11
drwx------ 2 tacacs12 tacacs12 4096 Mar 30 16:33 tacacs12
drwx------ 2 tacacs13 tacacs13 4096 Mar 30 16:33 tacacs13
drwx------ 2 tacacs14 tacacs14 4096 Mar 30 16:33 tacacs14
drwx------ 2 tacacs15 tacacs15 4096 Mar 30 16:33 tacacs15
drwx------ 2 tacacs2  tacacs2  4096 Mar 30 16:32 tacacs2
drwx------ 2 tacacs3  tacacs3  4096 Mar 30 16:32 tacacs3
drwx------ 2 tacacs4  tacacs4  4096 Mar 30 16:33 tacacs4
drwx------ 2 tacacs5  tacacs5  4096 Mar 30 16:33 tacacs5
drwx------ 2 tacacs6  tacacs6  4096 Mar 30 16:33 tacacs6
drwx------ 2 tacacs7  tacacs7  4096 Mar 30 16:33 tacacs7
drwx------ 2 tacacs8  tacacs8  4096 Mar 30 16:33 tacacs8
drwx------ 2 tacacs9  tacacs9  4096 Mar 30 16:33 tacacs9

```

/etc/pam.d/tacacs contains:

```
auth       sufficient     /lib/security/pam_tacplus.so debug include=/etc/tacplus_servers 
account    sufficient   /lib/security/pam_tacplus.so debug include=/etc/tacplus_servers priv-lvl=10
#account    sufficient   /lib/security/pam_exec.so /usr/local/bin/showenv.sh
#password   required     /lib/security/pam_cracklib.
#password   required     /lib/security/pam_pwdb.so shadow use_authtok
session    sufficient     /lib/security/pam_tacplus.so debug include=/etc/tacplus_servers

```

I also created /etc/libnss-tacplus.conf as follows:

```
[root@localhost ~]# cat /etc/libnss-tacplus.conf 
tacacs10:x:1010:1010::/home/tacacs10:/bin/bash

```

I tried that because that is was libnss-ato required to get around the incorrect password issue but that is not working in this case but worth trying.

Any help is appreciated.

Thanks.

**Comment by daveolson53** [comment]
stevetavve <notifications@github.com> wrote:

> Using Wireshark, I see that I am getting
> 
> Password: \b\n\r\177INCORRECT
> 
> from the Tacacs server even when I provide the correct password for the Tacacs
> user.

Which TACACS server are you using?  Can you turn on debugging on the
tacacs server, to see why it's rejecting the account (or password)?

> In the debug logs I see:
> 
> [root@localhost ~]# cat /var/log/debug.log
> Mar 30 16:39:13 localhost sshd[1199]: Invalid user tacacsAdmin from 10.254.1.180
> Mar 30 16:39:13 localhost sshd[1199]: input_userauth_request: invalid user tacacsAdmin [preauth]

This means the server doesn't think that is a valid account, or at
least, not valid from the system you are logging in on.

> Mar 30 16:39:34 localhost PAM-tacplus[1199]: 1 servers defined
> Mar 30 16:39:34 localhost PAM-tacplus[1199]: server[0] { addr=10.254.1.117:49, key='andy' }

> I've created the tacacs users tacacs0..15

That looks right.

> /etc/pam.d/tacacs contains:

Why do you have /etc/pam.d/tacacs?  You should have entries only in the
/etc/pam.d/common-* files.  If you install the sample tacplus pam file
in /usr/share/pam-configs, and then run pam-auth-update, it will make
the changes for you (unless you have customized your pam.d files too
much).

If you have customized pam.d files, I'd recommend by saving  your
changed files, going back to the pam defaults, and then using
pam-auth-update to setup the tacacs client, to be sure you have
everything correct, then start adding back your local mods.

> auth       sufficient     /lib/security/pam_tacplus.so debug include=/etc/tacplus_servers
> account    sufficient   /lib/security/pam_tacplus.so debug include=/etc/tacplus_servers priv-lvl=10
> #account    sufficient   /lib/security/pam_exec.so /usr/local/bin/showenv.sh
> #password   required     /lib/security/pam_cracklib.
> #password   required     /lib/security/pam_pwdb.so shadow use_authtok
> session    sufficient     /lib/security/pam_tacplus.so debug include=/etc/tacplus_servers
> 
> 
> I also created /etc/libnss-tacplus.conf as follows:
> 
> [root@localhost ~]# cat /etc/libnss-tacplus.conf
> tacacs10:x:1010:1010::/home/tacacs10:/bin/bash

That's wrong, it should be causing warning messages.

What you should be doing is including /etc/tacplus_servers,
and putting your server info and key in that file, so it's
only in one place:

# The include keyword allows centralizing the tacacs+ server information
# including the IP address and shared secret
include=/etc/tacplus_servers

And then in /etc/tacplus_servers:

server=10.254.1.117:49
secret=andy
debug=1

(I assume you already have something similar, from the debug output
you included).

Also be sure you have this in /etc/nsswitch.conf
   passwd: compat tacplus
(to begin with; when everything is working right, you'll
want tacplus first).

The fact that you get no "nss_tacplus" debug messages says to me
that libnss-tacplus isn't talking to the server.  You can verify
that is working by running:
	getent passwd tacacsAdmin
if you get no output, the tacacs server is saying that name isn't valid
(assuming you now get the nss_tacplus debug messages in the log).

It's much easier to debug that, than the full login process, so get
that working first.

I do have a bunch of tacacs cleanup and more features that I've been
working on, that I haven't yet pushed to github.   I'll be doing that
next week, most likely.

By the way, feel free to send email directly to my address below,
rather than through github, if you want.

Dave Olson
olson@cumulusnetworks.com

**Comment by daveolson53** [comment]
inactive project, no followup.
